version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install && npm --prefix ./functions/ install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: Linting
          command: npm run lint:dev
      - run:
          name: Inject Firebase DB and Google Maps keys
          command: npm run env-keys-config:override-keys
      - run:
          name: Testing
          command: npm run test:dev
      - run:
          name: Disallow indexing for dev site
          command: sed -i 's/<!-- <meta name="robots" content="noindex"> -->/<meta name="robots" content="noindex">/' src/index.html
      - run:
          name: Building
          command: npm run build:dev
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - functions
            - package.json
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/project
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: Deploy Develop to Firebase
          command: npm run firebase:deploy-dev -- --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
